# "docker compose -p echochatws-staging -f docker-compose-staging.yml --env-file .env.staging up --build"
version: "4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.staging
    environment:
      - APP_STAGE=staging
    restart: unless-stopped
    ports:
      - "127.0.0.1:20013:${APP_PORT}"
    networks:
      - echochat-staging_network-1

  obsv-prometheus:
    image: prom/prometheus
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - '127.0.0.1:9092:9090'
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml # --web.listen-address=:9091
    networks:
      - echochat-staging_network-1

networks:
    echochat-staging_network-1:
        external: true