# "docker compose -p echochatws-staging -f docker-compose-staging.yml --env-file .env.staging up --build"
version: "4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.staging
    environment:
      - APP_STAGE=staging
    restart: no
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - echochat-staging_network-1

networks:
    echochat-staging_network-1:
        external: true