global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus_ws
    static_configs:
      - targets:
          - localhost:9090
  - job_name: 'echo_ws'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: [ 'app:1323' ]